-- >>> KEYMAPS
vim.keymap.set("n", "Q", "<nop>", { noremap = true, silent = true })
vim.keymap.set("n", "<leader>w", ":w<cr>", { noremap = true, silent = true })
vim.keymap.set("n", "<esc>", ":noh<cr>", { noremap = true, silent = true })
vim.keymap.set("n", "n", "nzzzv", { noremap = true, silent = true })
vim.keymap.set("n", "N", "Nzzzv", { noremap = true, silent = true })
vim.keymap.set("n", "*", "*zz", { noremap = true, silent = true })
vim.keymap.set("n", "#", "#zz", { noremap = true, silent = true })
vim.keymap.set("n", "g*", "g*zz", { noremap = true, silent = true })
vim.keymap.set("n", "g#", "g#zz", { noremap = true, silent = true })
vim.keymap.set("n", "<c-d>", "<c-d>zz", { noremap = true, silent = true })
vim.keymap.set("n", "<c-u>", "<c-u>zz", { noremap = true, silent = true })
vim.keymap.set("v", "P", [["_dP]], { noremap = true, silent = true })
vim.keymap.set({ "n", "v" }, "<leader>d", [["_d]], { noremap = true, silent = true })
vim.keymap.set({ "n", "x", "v" }, "<leader>x", [["_x]], { noremap = true, silent = true })
vim.keymap.set("n", "Y", "yg$", { noremap = true, silent = true })
vim.keymap.set("n", "J", "mzJ`z", { noremap = true, silent = true })
vim.keymap.set("n", "<m-j>", ":m .+1<cr>==", { noremap = true, silent = true })
vim.keymap.set("n", "<m-k>", ":m .-2<cr>==", { noremap = true, silent = true })
vim.keymap.set("v", "<m-h>", ":m '>+1<cr>gv=gv", { noremap = true, silent = true })
vim.keymap.set("v", "<m-l>", ":m '<-2<cr>gv=gv", { noremap = true, silent = true })
vim.keymap.set("v", "<", "<gv", { noremap = true, silent = true })
vim.keymap.set("v", ">", ">gv", { noremap = true, silent = true })
vim.keymap.set("n", "]c", ":cnext<cr>", { noremap = true, silent = true })
vim.keymap.set("n", "[c", ":cprev<cr>", { noremap = true, silent = true })
vim.keymap.set("n", "<F1>", ":cnext<cr>", { noremap = true, silent = true })
vim.keymap.set("n", "<F3>", ":cprev<cr>", { noremap = true, silent = true })

vim.keymap.set("n", "<leader>fo", ":Explore<cr>", { noremap = true, silent = true })
