-- TODO:
--   - more ftplugins
--   - native lsp for work
--   - use builtin snippets and autocomplete for text and files
--   - marks to replace harpoon
--   - colors
--   - fennel
--   - debugging
--   - custom treesitter-context
--   - folding
--
-- references:
--   - colors:
--     - https://youtu.be/CXVDfg3W9Jk?si=v_PS6OAxvUjhjUoM
--     - https://youtu.be/LUtgHPOeefA?si=JxLQanuFo0hRGlVD
--   - marks:
--     - https://www.reddit.com/r/neovim/comments/1m8v8lw/what_wellknown_neovim_features_do_you_struggle_to/?utm_source=share&utm_medium=mweb3x&utm_name=mweb3xcss&utm_term=1
--     - https://youtu.be/nJR5lHBrviI?si=qOOkSu-5E3DVBl1A
--     - https://youtu.be/hUyiJzDiHik?si=5X4jGcCBxXjhUZwr
--   - snippets:
--     - https://www.reddit.com/r/neovim/comments/1cxfhom/builtin_snippets_so_good_i_removed_luasnip/
--     - https://gist.github.com/MariaSolOs/2e44a86f569323c478e5a078d0cf98cc
--   - debugging:
--     - zed: https://zed.dev/docs/development/debuggers
--     - i MIGHT use a plugin for debugging, if i cannot setup zed for that
--     - nvim dap: https://youtu.be/cxpWjlNXeQA?si=vbocJxlP2odku6Yp
--     - https://www.reddit.com/r/neovim/comments/1jyfsfh/i_cant_see_vector_items_debugging_rust/?utm_source=share&utm_medium=mweb3x&utm_name=mweb3xcss&utm_term=1
--     - https://youtu.be/lyNfnI-B640?si=hkDQmjJsiB0Uwes5
--   - native lsp:
--     - https://youtu.be/tdhxpn1XdjQ?si=GFaBKLcVtQ75xYwO
--   - i might want to write my config in fennel...
--     - https://fennel-lang.org/
--     - https://github.com/Olical/nfnl
--     - https://github.com/rafaeldelboni/cajus-nfnl?tab=readme-ov-file
--     - https://github.com/Samy-33/dotfiles/tree/3057a7c28001e030808bd06b4f8dd06dc90a7bae/dotcom/.config/nvim
--   - folding:
--     - https://www.reddit.com/r/neovim/comments/1jmqd7t/sorry_ufo_these_7_lines_replaced_you/
--
--   - videos on pluginless neovim:
--     - https://youtu.be/XA2WjJbmmoM?si=nrSvG-iiLWvyPZn6
--     - https://youtu.be/I5kT2c2XX38?si=9AJUw-moMT5hUvFk
--     - https://youtu.be/HiAs7oNDyh0?si=ma-xzh6JFv52z2eI
--     - https://youtu.be/skW3clVG5Fo?si=rR_Uijd9CWAGRNWG
--     - https://youtu.be/mQ9gmHHe-nI?si=IcPMAwCk_9DPJpDi
--     - https://youtu.be/xGkL2N8w0H4?si=Zfmop2Pq6x8Ctip3
--   - netrw:
--     - https://youtu.be/g2LTTq9hkbU?si=fbZ2aGq63l6MpV-2
--     - https://youtu.be/nbKkKbENgd8?si=nTf4lPt8YilgpBt9
--     - https://youtu.be/nDGhjk4Eqbc?si=3_SowkNGXDNIY8cp
--     - https://youtu.be/3lqzc77carU?si=K9cYv7lbbLIwO7O-
--     - https://youtu.be/VNDoMhKVdQM?si=ik-IpCYDMdXgSOuD
--     - https://youtu.be/9UxMvz6u1K4?si=jIZzdHTt48vOad5I
--     - https://youtu.be/GyPXYF6jgwk?si=8qhkJshwZF2h5p81
--
-- KEYBINDS I SHOULD REMEMBER:
--   mode | bind       | effect
--   x    | <c-r>%     | paste current file name into command line
--   x    | <c-r><c-l> | paste current line into command line
--   x    | @:<cr>     | repeat last command
--   n    | <c-^>      | switch to alternate (last) buffer
--   n    | <c-w>+     | increase window size vertically
--   n    | <c-w>-     | decrease window size vertically
--   n    | <c-w><     | increase window size to the left
--   n    | <c-w>>     | increase window size to the right

require("tvim.vimsettings")
require("tvim.ui")
require("tvim.keymaps")
require("tvim.user_commands")
require("tvim.navigation")
